# @(#) $Header: K:/BCT_Development/vxWorks/Common/rcs/makefile.rules 1.7 2002/11/27 15:01:04 jl11312 Exp jl11312 $
#
# Makefile.rules - common makefile rules for vxWorks
#
# $Log: makefile.rules $
# Revision 1.5  2002/09/06 13:08:47  jl11312
# - correct dependency generation rule to properly handle source files not in the current directory
# Revision 1.4  2002/08/28 16:46:13  sb07663
# added rule to create a bin/.o file from a .cpp
# Revision 1.3  2002/05/16 17:39:03  jl11312
# - changed assembly source from .S to .s
# Revision 1.2  2002/04/19 17:28:54  jl11312
# - moved output directory creation to .o build rule
# Revision 1.1  2002/04/18 14:27:47  jl11312
# Initial revision
#

ifndef MAKEFILE_RULES_INCLUDED
MAKEFILE_RULES_INCLUDED := 1

$(CPU)/%.o:%.c
	@if not exist $(CPU) mkdir $(CPU)
	$(CC) $(CCFLAGS) $< -o $@

$(CPU)/%.o:%.cpp
	@if not exist $(CPU) mkdir $(CPU)
	$(CXX) $(CXXFLAGS) $< -o $@

bin/%.o:%.cpp
	@if not exist bin mkdir bin
	$(CXX) $(CXXFLAGS) $< -o $@

$(CPU)/%.o:%.s
	@if not exist $(CPU) mkdir $(CPU)
	$(AS) $(ASFLAGS) $< -o $@

.dfile/%.d:%.c
	@echo Rebuilding dependency file for $<
	@if not exist .dfile mkdir .dfile
	@rm -f $(CPU)/$(notdir $(subst .c,.o,$<))
	@rm -f $@.tmp
	@$(CC) -M $(CPPFLAGS) $< >$@.tmp
	@sed -e "1s/$(subst .d,\.o,$(@F))[ :]*/\$(subst .c,.o,$(subst /,\/,$(CPU)/$(notdir $<))) $(subst /,\/,$@) : /g" < $@.tmp > $@
	@rm -f $@.tmp

.dfile/%.d:%.cpp
	@echo Rebuilding dependency file for $<
	@if not exist .dfile mkdir .dfile
	@rm -f $(CPU)/$(notdir $(subst .cpp,.o,$<))
	@rm -f $@.tmp
	@$(CC) -M $(CPPFLAGS) $< >$@.tmp
	@sed -e "1s/$(subst .d,\.o,$(@F))[ :]*/\$(subst .cpp,.o,$(subst /,\/,$(CPU)/$(notdir $<))) $(subst /,\/,$@) : /g" < $@.tmp > $@
	@rm -f $@.tmp

.dfile/%.d:%.s
	@echo Rebuilding dependency file for $<
	@if not exist .dfile mkdir .dfile
	@rm -f $(CPU)/$(notdir $(subst .s,.o,$<))
	@rm -f $@.tmp
	@$(CC) -M $(CPPFLAGS) $< >$@.tmp
	@sed -e "1s/$(subst .d,\.o,$(@F))[ :]*/\$(subst .s,.o,$(subst /,\/,$(CPU)/$(notdir $<))) $(subst /,\/,$@) : /g" < $@.tmp > $@
	@rm -f $@.tmp

endif

