# $Header$
# $Log: makefile.vx $
# Revision 1.1  2005/01/18 22:57:00Z  jl11312
# Initial revision
#

.PHONY: all
all: check_opt_change app

#
# MAINDIR should be set to the relative path from this makefile directory
# to the base trima project directory.  MAINDIR must use \ (DOS/Windows
# style) directory separators if they are needed.
#
MAINDIR = ..\..\..\..
ADDN_INCDIR = -I$(MAINDIR) -I$(MAINDIR)/include

include $(MAINDIR)/makefile.vxc

#
# The following should define all of the source files of each type
# to be compiled for the executable
#
APP_NAME := test2
test2_dir = out
test2_cxx_files = test2.cpp test2_main.cpp
test2_libs = $(MAINDIR)/config_file_support/lib/libconfigfilesupport.a
include $(MAINDIR)/makefile.process_app

#
# This is the standard makefile for Trima applications
#
include $(MAINDIR)/makefile.build_apps
app : $(APP_LIST)
test2.out : libconfigfilesupport.a

